CAPS = {
    # "deviceName": "41180608000071",
    # "deviceName": "3EP7N19401002574",
    "deviceName": "192.168.1.108:5555",
    # "udid": "192.168.1.97:5555",
    "automationName": "Uiautomator2",
    "platformName": "Android",
    "platformVersion": "7.1.2",
    # "appWaitActivity": "zhiyun.com.mirrorplusandroid.freeee.activity.FaceActivity",
    "appPackage": "zhiyun.com.mirrorplusandroid.freeee",
    # "appPackage": "zhiyun.com.mirrorplusandroid",
    "appActivity": "zhiyun.com.mirrorplusandroid.activity.WelcomeActivity",
    "unicodeKeyboard": True,
    "resetKeyboard": True,
    # "autoWebview": True,
}
